/*
    Hit is a high speed transactional database for handling millions
    of updates with comfort and ease. 

    Copyright (C) 2013  Balraja Subbiah

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

package org.hit.messages;

import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import org.hit.communicator.Message;
import org.hit.communicator.NodeID;
import org.hit.db.model.Mutation;

/**
 * THe message that will be generated by a newly started slave to load data
 * alloted to it by master from another node.
 * 
 * @author Balraja Subbiah
 */
public class DataLoadResponse extends Message
{
    private String myTableName;
    
    private Mutation myDataLoadResponseMutation;
    
    /**
     * CTOR
     */
    public DataLoadResponse()
    {
        this(null, null, null);
    }

    /**
     * CTOR
     */
    public DataLoadResponse(NodeID senderID, 
                            String tableName,
                            Mutation dataLoadResponse)
    {
        super(senderID);
        myTableName = tableName;
        myDataLoadResponseMutation = dataLoadResponse;
    }
    
    /**
     * Returns the value of tableName
     */
    public String getTableName()
    {
        return myTableName;
    }

    /**
     * Returns the value of dataLoadResponseMutation
     */
    public Mutation getDataLoadResponseMutation()
    {
        return myDataLoadResponseMutation;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void readExternal(ObjectInput in)
        throws IOException, ClassNotFoundException
    {
        super.readExternal(in);
        myTableName = in.readUTF();
        myDataLoadResponseMutation = (Mutation) in.readObject();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void writeExternal(ObjectOutput out) throws IOException
    {
        super.writeExternal(out);
        out.writeUTF(myTableName);
        out.writeObject(myDataLoadResponseMutation);
    }
}
