/*
    Hit is a high speed transactional database for handling millions
    of updates with comfort and ease.

    Copyright (C) 2013  Balraja Subbiah

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

package org.hit.facade;

import java.util.Set;

import org.hit.communicator.NodeID;
import org.hit.db.model.Schema;

/**
 * Defines the contract for the response generated by the facade when a table
 * is successfully created in the database.
 *
 * @author Balraja Subbiah
 */
public class TableCreationResponse
{
    private final Set<NodeID> myAffectedNodes;

    private final Schema myTableSchema;

    /**
     * CTOR
     */
    public TableCreationResponse(Set<NodeID> affectedNodes, Schema tableSchema)
    {
        myAffectedNodes = affectedNodes;
        myTableSchema = tableSchema;
    }

    /**
     * Returns the value of affectedNodes
     */
    public Set<NodeID> getAffectedNodes()
    {
        return myAffectedNodes;
    }

    /**
     * Returns the value of tableSchema
     */
    public Schema getTableSchema()
    {
        return myTableSchema;
    }
}
